export interface Publication {
  id: string;
  title: string;
  type: PublicationType;
  status: PublicationStatus;
  year: number;
  authors: Author[];
  content: PublicationContent;
  coverImage?: string;
  isbn?: string;
  doi?: string;
  language: string;
  sections: PublicationSection[];
  generatedAt?: Date;
  publishedAt?: Date;
  archivedAt?: Date;
}

export enum PublicationType {
  ANNUAL_BOOK = 'ANNUAL_BOOK',
  SCIENTIFIC_PAPER = 'SCIENTIFIC_PAPER',
  REPORT = 'REPORT',
  NEWSLETTER = 'NEWSLETTER',
  BROCHURE = 'BROCHURE'
}

export enum PublicationStatus {
  DRAFT = 'DRAFT',
  IN_REVIEW = 'IN_REVIEW',
  APPROVED = 'APPROVED',
  PUBLISHED = 'PUBLISHED',
  ARCHIVED = 'ARCHIVED'
}

export interface Author {
  id: string;
  name: string;
  affiliation?: string;
  email?: string;
  order: number;
}

export interface PublicationContent {
  introduction: string;
  summary: string;
  dataSources: string[];
  autoGenerated: boolean;
}

export interface PublicationSection {
  id: string;
  title: string;
  order: number;
  type: SectionType;
  content: SectionContent;
  charts?: Chart[];
  tables?: Table[];
  images?: Image[];
}

export enum SectionType {
  TEXT = 'TEXT',
  DATA_ANALYSIS = 'DATA_ANALYSIS',
  SPECIES_CATALOG = 'SPECIES_CATALOG',
  MISSION_REPORT = 'MISSION_REPORT',
  ENVIRONMENTAL_DATA = 'ENVIRONMENTAL_DATA',
  CUSTOM = 'CUSTOM'
}

export interface SectionContent {
  text?: string;
  dataSource?: string;
  filters?: Record<string, unknown>;
  template?: string;
}

export interface Chart {
  id: string;
  type: ChartType;
  title: string;
  data: unknown;
  config: ChartConfig;
}

export enum ChartType {
  LINE = 'LINE',
  BAR = 'BAR',
  PIE = 'PIE',
  SCATTER = 'SCATTER',
  MAP = 'MAP'
}

export interface ChartConfig {
  xAxis?: string;
  yAxis?: string;
  colors?: string[];
  showLegend?: boolean;
  showGrid?: boolean;
}

export interface Table {
  id: string;
  title: string;
  headers: string[];
  rows: unknown[][];
  pagination?: boolean;
}

export interface Image {
  id: string;
  url: string;
  caption?: string;
  alt?: string;
}

export interface ExportOptions {
  format: ExportFormat;
  sections?: string[];
  includeCharts?: boolean;
  includeImages?: boolean;
  quality?: ExportQuality;
}

export enum ExportFormat {
  PDF = 'PDF',
  WEB = 'WEB',
  EPUB = 'EPUB',
  DOCX = 'DOCX'
}

export enum ExportQuality {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH'
}
